name: Test SSH Connection
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Test SSH connection using appleboy/ssh-action
      - name: Test SSH connection
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: 147.79.118.232
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: echo 'SSH connection successful'
