name: Test SSH Connection
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Create the SSH key file
      - name: Create SSH key file
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > my_ssh_key
          chmod 600 my_ssh_key

      # Step 3: Test SSH connection manually with more verbose output
      - name: Test SSH connection
        run: |
          ssh -vvv -i my_ssh_key -o StrictHostKeyChecking=no root@147.79.118.232 "echo 'SSH connection successful'"

      # Step 4: Clean up the SSH key file
      - name: Clean up SSH key file
        run: |
          rm my_ssh_key

      # Step 5: Print a success message
      - name: Success message
        run: |
          echo "SSH connection successful"
