name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create SSH key file
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > my_ssh_key
          chmod 600 my_ssh_key

      - name: Sync files to VPS using rsync (incremental sync)
        run: |
          set -x
          rsync -avz --exclude=.git --exclude=node_modules --exclude=build -e 'ssh -i my_ssh_key -o StrictHostKeyChecking=no' ./ deployuser@147.79.118.232:/var/www/mcfolio

      - name: Install dependencies and build frontend
        run: |
          ssh -i my_ssh_key -o StrictHostKeyChecking=no deployuser@147.79.118.232 << 'EOF'
            cd /var/www/mcfolio/client
            # Use npm ci for faster installation
            npm ci
            npm run build
          EOF

      - name: Restart Nginx and PM2 with zero-downtime reload
        run: |
          ssh -i my_ssh_key -o StrictHostKeyChecking=no deployuser@147.79.118.232 << 'EOF'
            sudo systemctl restart nginx
            pm2 reload all --update-env
          EOF
