#deploy.yml
name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Create the SSH key file
      - name: Create SSH key file
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > my_ssh_key
          chmod 600 my_ssh_key

      # Step 3: Deploy to VPS
      - name: Deploy to VPS
        run: |
          set -x
          scp -i my_ssh_key -o StrictHostKeyChecking=no -r * root@147.79.118.232:/var/www/mcfolio
